version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - ./app:/app/app
      - sqlite_data:/app/data
    restart: always

volumes:
  sqlite_data:
