"""Add user id for events

Revision ID: 324f3e2235d6
Revises: 39d437bcc994
Create Date: 2025-07-07 15:50:03.128389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324f3e2235d6'
down_revision: Union[str, Sequence[str], None] = '39d437bcc994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Usando batch mode para compatibilidad con SQLite
    with op.batch_alter_table('events') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Usando batch mode para compatibilidad con SQLite
    with op.batch_alter_table('events') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
