"""Add prize and start time

Revision ID: e36fd6701348
Revises: 107971ea5159
Create Date: 2025-07-07 21:16:29.748788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36fd6701348'
down_revision: Union[str, Sequence[str], None] = '107971ea5159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('prize', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'prize')
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###
