name: Build and Test FastAPI App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create SQLite data directory
      run: mkdir -p data
        
    - name: Run Alembic migrations
      run: alembic upgrade head
      env:
        DATABASE_URL: sqlite:///./data/app.db
      
    - name: Run tests (if available)
      run: |
        pytest || echo "No tests found, continuing anyway..."
      continue-on-error: true
      
    - name: Build Docker image (without push)
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: imagineapps-backend:latest
        
    - name: Test Docker image
      run: |
        docker run --rm imagineapps-backend:latest echo "Docker image built successfully!"
