name: Deploy FastAPI App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create SQLite data directory
      run: mkdir -p data
        
    - name: Run Alembic migrations
      run: alembic upgrade head
      env:
        DATABASE_URL: sqlite:///./data/app.db
      
    - name: Run tests
      run: |
        pytest
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}:${{ github.sha }}
        
    - name: Deploy to Azure Web App
      if: github.event_name != 'pull_request'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}:${{ github.sha }}
